In [2]:
import numpy as np

In [3]:
# Linear Regression --

class LinearRegression :
    def __init__(self, learning_rate= 0.01, n_iter=1000):
        self.bias = None
        self.weights = None
        self.lr = learning_rate
        self.n_iter = n_iter

    def fit(self, X, y):
        m, n = X.shape #num of samples, features

        # step - 1 : initialize random val
        self.bias = 0
        self.weights = np.zeros(n)


        for i in range(self.n_iter) :
            # step - 2 : y_pred cost fun
            y_pred = self.bias + np.dot(X, self.weights) #0o + (01.x1 , 02.x2, ...)
    
            # step - 3 : derivative 
            db = (1/m) * np.sum(y_pred - y)
            dw = (1/m) * np.dot(X.T , (y_pred - y))  
            #dot becz data is stored in matrix , x ko trandpose kiya 
    
            # step - 4 : convergence
            self.bias -= self.lr* db
            self.weights -= self.lr* dw

    def predict(self, X) :
        y_pred = self.bias + np.dot(X, self.weights)
        return y_pred

In [4]:
X = np.array([ [1], [2], [3], [4], [5] ])
y = np.array([2,4,6,8,10])

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)
print(y_pred)

[2.06850809 4.04226297 6.01601785 7.98977273 9.96352761]


In [5]:
# Linear Regression with OLS --

class LinearRegressionOLS:
    def __init__(self):
        self.bias = None
        self.weights = None
        
    def fit(self, X, y):
        m , n = X.shape

        X_b = np.c_[np.ones((m, 1)), X]

        #normal eqn
        # theta = np.dot( np.linalg.inv(np.dot(X_b.T, X_b)), np.dot(X_b.T, y))
        theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
        
        self.bias = theta[0]
        self.weights = theta[1:]
        
    def predict(self, X) :
        y_pred = self.bias + np.dot(X, self.weights)
        return y_pred

In [6]:
X = np.array([ [1], [2], [3], [4], [5] ])
y = np.array([2,4,6,8,10])

model = LinearRegressionOLS()
model.fit(X, y)

y_pred = model.predict(X)
print(y_pred)
print(model.bias)
print(model.weights)

[ 2.  4.  6.  8. 10.]
5.662137425588298e-15
[2.]


In [7]:
# Logistic Regression --

class LogisticRegression :
    def __init__(self, learning_rate= 0.01, n_iter=1000):
        self.bias = None
        self.weights = None
        self.lr = learning_rate
        self.n_iter = n_iter

    def _sigmoid(self, z) :
        return (1/ (1+ np.exp(-z)) )

    def fit(self, X, y):
        m, n = X.shape #num of samples, features

        # step - 1 : initialize random val
        self.bias = 0
        self.weights = np.zeros(n)

        for i in range(self.n_iter) :
            z = self.bias + np.dot(X, self.weights)
            y_pred = self._sigmoid(z)

            # step - 3 : derivative 
            db = (1/m) * (y_pred - y)
            dw = (1/m) * np.dot(X.T , (y_pred - y))  
            #dot becz data is stored in matrix , x ko trandpose kiya 
    
            # step - 4 : convergence
            self.bias -= self.lr* db
            self.weights -= self.lr* dw

    def get_prob(self,  x):
            z = self.bias + np.dot(X, self.weights)
            return self._sigmoid(z)
        # in btw 0 - 1
        
    def predict(self, X, threshold = 0.5) :
        prob = self.get_prob(X)
        y_pred_bool = prob >= threshold
        return y_pred_bool.astype(int)
        

In [8]:
X = np.array([ [1,2], [2,3], [3,4], [4,5] ])
y = np.array( [0,0,1,1])

model = LogisticRegression()
model.fit(X , y)

y_pred = model.predict(X)
print(y_pred)

print(model.get_prob(X))

[0 0 1 1]
[0.28294786 0.33688991 0.81585258 0.85485553]


In [8]:
# KNN CLASSIFIER --

class KNNClassifier :
    def __init__(self, k=3) :
        self.k = k

    def _euclidean_dist(self, x1, x2):
        return np.sqrt(np.sum((x1-x2)**2))

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def _predict_one (self, x):
        dist = [self._euclidean_dist(x, X_train) for x_train in self.X_train]

        knn_indices = np.argsort(dist)[:self.k]  #closest num ke index pos

        knn_classes = [self.y_train[i] for i in knn_indices]

        majority_class = np.argmax(np.bincount(knn_classes))  
        #bincount stores - freq of classes
        #argmax return index with max frequency 

        return majority_class

    def predict(self, X):
        y_pred = [self._predict_one(x) for x in X]
        return np.array(y_pred)

        

In [9]:
# KNN --

X_train = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5],
    [6,5],
    [7,7]
])

y_train = np.array([0,0,0,1,1])

X_test = np.array([
    [2,2],
    [6,6]
])

model = KNNClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(y_pred)

[0 0]


In [10]:
import pandas as pd
import seaborn as sns
import numpy as np
# visualizee -

X_train_df = pd.DataFrame(X_train, columns = ["x1", "x2"])
X_train_df["label"] = y_train

sns.scatterplot(
    data = X_train_df,
    x = "x1",
    y = "x2",
    hue = "label"
)


X_test_df = pd.DataFrame(X_test, columns=["x1", "x2"])


sns.scatterplot(
    data = X_test_df,
    x = "x1",
    y = "x2",
    color = "black",
    marker = "A",
    label = "Test Points"
)

ValueError: Length of values (5) does not match length of index (6)