In [1]:
import numpy as np

In [2]:
# create - from list

np_arr = np.array([1,23,3,4,5,6])
print(np_arr, type(np_arr), np_arr.dtype, np_arr.shape)

np_arr2 = np.array([1,2,4,5,"stringg"])
print(np_arr2, type(np_arr2), np_arr2.dtype, np_arr2.shape)

# 2d arr

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d, type(arr2d), arr2d.dtype, arr2d.shape)


[ 1 23  3  4  5  6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '4' '5' 'stringg'] <class 'numpy.ndarray'> <U21 (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [3]:
# create from scratch
        # zeros, ones, eye, full, arange, linspace

arr1 = np.zeros((2,3), dtype = "int64")
print(arr1, arr1.shape)

arr2 = np.ones((5,))
print(arr2, arr2.shape)

arr3 = np.full((3,4),100)
print(arr3, arr3.shape)

arr4 = np.eye((2))
print(arr4, arr4.shape)

arr5 = np.arange(0,11,2)
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4)
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0.]
 [0. 1.]] (2, 2)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [4]:
# propertiess

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)


(3, 3)
int64
9
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [5]:
# operation on arr - 

arr = np.array([[1,2,4], [6,8,4]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()    # 2d -> 1d
print(flattened, flattened.shape)

[[1 2 4]
 [6 8 4]] (2, 3)
[[1 2]
 [4 6]
 [8 4]] (3, 2)
[1 2 4 6 8 4] (6,)


In [6]:
# indexing

arr = np.array([1,2,3,5,56,64,3])
print(arr[0])

arr2 = np.array([[1,2,4], [6,8,4]])
print(arr2[1][1])

# fancy index
arr = np.array([1,2,3,5,56,64,3])
idx = [0,3,5]
print(arr[idx])

# boolean idx 
arr = np.array([1,2,3,5,56,64,3])
print(arr[arr>5])
print(arr[arr%5 == 0])
print(arr[arr<5])

1
8
[ 1  5 64]
[56 64]
[5]
[1 2 3 3]


In [7]:
# slicing 

arr = np.array([1,2,3,5,56,64,3])
print(arr[1:5])
print(arr[3:])
print(arr[:4])
print(arr[::2])

[ 2  3  5 56]
[ 5 56 64  3]
[1 2 3 5]
[ 1  3 56  3]


In [8]:
# copy vs view
# list
nums = [1,2,3,4,5]
sub_list = nums[1:3]   #copy 
print(sub_list)

sub_list[0] = 200      #changed in copy
print(nums)   #no change
print(sub_list[0])     #change occr in copy

# np array
arr = np.array([1,3,4,5,7,8])
sub_arr = arr[3:]
sub_arr2 = arr[3:].copy()
print(sub_arr)
print(sub_arr2)

sub_arr[0] = 200      #changed in view
print(arr)   #changed
print(sub_arr[0])     #changed

[2, 3]
[1, 2, 3, 4, 5]
200
[5 7 8]
[5 7 8]
[  1   3   4 200   7   8]
200


In [9]:
# datatype --

arr = np.array([1,2,3,4,5,6])
print(arr, arr.dtype)

arr2 = np.array([1,2,3.5,4,5,6])
print(arr2, arr2.dtype)

arr3 = np.array([1,2,3.5,4,"5",6])
print(arr3, arr3.dtype)

# complex-
arr4 = np.array([3+5j])
arr5 = np.array([2+3j])
print(arr4, arr4.dtype)
print(arr4+arr5)

# object-

obj_arr = np.array(["prime", {1,2,3}, 3.14])
print(obj_arr, obj_arr.dtype)

[1 2 3 4 5 6] int64
[1.  2.  3.5 4.  5.  6. ] float64
['1' '2' '3.5' '4' '5' '6'] <U32
[3.+5.j] complex128
[5.+8.j]
['prime' {1, 2, 3} 3.14] object


In [17]:
# multi dimensional array-

arr2d = np.array([[1,2,3], [4,5,6], [2,5,7]])
print(arr2d)

print(np.sum(arr2d))


sum_of_col = np.sum(arr2d, axis = 0)
print(sum_of_col)
sum_of_row = np.sum(arr2d, axis = 1)
print(sum_of_row)

# slicing
print(arr2d[0:2, 1:2])
print(arr2d[2:3, 1:3])

[[1 2 3]
 [4 5 6]
 [2 5 7]]
35
[ 7 12 16]
[ 6 15 14]
[[2]
 [5]]
[[5 7]]


In [22]:
# 3d array-- 

arr3d = np.array([ [[1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]] ])
print(arr3d, arr3d.shape)

# indexing
print(arr3d[0, 1, 1])
print(arr3d[1, 0, 1])

# slicing 
print(arr3d[:, 0, :])   # [ box , row , col]
print(arr3d[0, 1, :])
print(arr3d[1, :, 1])

arr3d[:, 0, :] = 99
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
8
[[1 2]
 [7 8]]
[3 4]
[ 8 10 12]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [23]:
# vactorization

arr = np.array([1,2,3,4,5,6])
arr2 = np.array([5,6,7,8,9,4])

print(arr ** 2)
print(arr2 + arr)

[ 1  4  9 16 25 36]
[ 6  8 10 12 14 10]


In [30]:
# broadcasting --
# rule should be equal or one
arr = np.array([1,2,3,4,5])    # (1,5)
arr2 = np.array([[5,6,7,8,9], [1,2,3,4,5]])   # (2,5)

print(arr.shape)
print(arr2.shape)

print(arr + arr2)    #possible

(5,)
(2, 5)
[[ 6  8 10 12 14]
 [ 2  4  6  8 10]]


In [34]:
# broadcasting is used to perform normalization -
            # transforming value so that they get fit!

arr = np.array([ [1,2], [3,4] ])

mean = np.mean(arr)     # sum of val/ total num of val
std_dev = np.std(arr)   # root(summ(value - mean)^2 / n)

norm_arr = (arr - mean) / std_dev
print(norm_arr)

print("mean:", mean)
print("std:",std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
mean: 2.5
std: 1.118033988749895


In [39]:
# MATHEMATICAL FUN -

# aggregation
arr = np.array([1,2,3,4,5])  
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))   #index of min val
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))   # (xi - mean )^2 / n

15
120
1
5
0
4
3.0
1.4142135623730951
3.0


In [40]:
# power fun- 

arr = np.array([1,2,3,4,5]) 
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

# log
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [41]:
# rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

# 
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
